version: '3.9'

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - "./scripts/:/docker-entrypoint-initdb.d/"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  app:
    ports:
      - 8916:8916
    build:
      context: ./
      dockerfile: ./build/package/Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
      - redis

volumes:
  redis:
    driver: local