// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "the-coolest-shuffler/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// CardsRepository is an autogenerated mock type for the CardsRepository type
type CardsRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: codes, values, suits
func (_m *CardsRepository) Get(codes []string, values []string, suits []string) []model.Card {
	ret := _m.Called(codes, values, suits)

	var r0 []model.Card
	if rf, ok := ret.Get(0).(func([]string, []string, []string) []model.Card); ok {
		r0 = rf(codes, values, suits)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Card)
		}
	}

	return r0
}

type mockConstructorTestingTNewCardsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCardsRepository creates a new instance of CardsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCardsRepository(t mockConstructorTestingTNewCardsRepository) *CardsRepository {
	mock := &CardsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
