version: "1.0.0"
postgres:
  host: "the-coolest-shuffler_postgres_1"
  port: "5432"
  database: "postgres"
  user: "postgres"
  password: "postgres"
  timezone: "America/Fortaleza"
  sslmode: "disable"
redis:
  host: "the-coolest-shuffler_redis_1"
  port: "6379"
  database: 0
  password: ""
app:
  host: "the-coolest-shuffler_app_1"
  port: "8916"
