CREATE TABLE cards (
    "order" serial, 
    "code" varchar(2) NOT NULL UNIQUE PRIMARY KEY,
    "value" varchar(5) NOT NULL,
    "suit" varchar(8) NOT NULL
);

INSERT INTO 
    cards ("code", "value", "suit") 
VALUES 
    ('AS', 'ACE', 'SPADES'),
    ('2S', '2', 'SPADES'),
    ('3S', '3', 'SPADES'),
    ('4S', '4', 'SPADES'),
    ('5S', '5', 'SPADES'),
    ('6S', '6', 'SPADES'),
    ('7S', '7', 'SPADES'),
    ('8S', '8', 'SPADES'),
    ('9S', '9', 'SPADES'),
    ('0S', '10', 'SPADES'),
    ('JK', 'JACK', 'SPADES'),
    ('QS', 'QUEEN', 'SPADES'),
    ('KS', 'KING', 'SPADES'),
    -- 
    ('AD', 'ACE', 'DIAMONDS'),
    ('2D', '2', 'DIAMONDS'),
    ('3D', '3', 'DIAMONDS'),
    ('4D', '4', 'DIAMONDS'),
    ('5D', '5', 'DIAMONDS'),
    ('6D', '6', 'DIAMONDS'),
    ('7D', '7', 'DIAMONDS'),
    ('8D', '8', 'DIAMONDS'),
    ('9D', '9', 'DIAMONDS'),
    ('0D', '10', 'DIAMONDS'),
    ('JD', 'JACK', 'DIAMONDS'),
    ('QD', 'QUEEN', 'DIAMONDS'),
    ('KD', 'KING', 'DIAMONDS'),
    --
    ('AC', 'ACE', 'CLUBS'),
    ('2C', '2', 'CLUBS'),
    ('3C', '3', 'CLUBS'),
    ('4C', '4', 'CLUBS'),
    ('5C', '5', 'CLUBS'),
    ('6C', '6', 'CLUBS'),
    ('7C', '7', 'CLUBS'),
    ('8C', '8', 'CLUBS'),
    ('9C', '9', 'CLUBS'),
    ('0C', '10', 'CLUBS'),
    ('JC', 'JACK', 'CLUBS'),
    ('QC', 'QUEEN', 'CLUBS'),
    ('KC', 'KING', 'CLUBS'),
    --
    ('AH', 'ACE', 'HEARTS'),
    ('2H', '2', 'HEARTS'),
    ('3H', '3', 'HEARTS'),
    ('4H', '4', 'HEARTS'),
    ('5H', '5', 'HEARTS'),
    ('6H', '6', 'HEARTS'),
    ('7H', '7', 'HEARTS'),
    ('8H', '8', 'HEARTS'),
    ('9H', '9', 'HEARTS'),
    ('0H', '10', 'HEARTS'),
    ('JH', 'JACK', 'HEARTS'),
    ('QH', 'QUEEN', 'HEARTS'),
    ('KH', 'KING', 'HEARTS');